def load_figures(filepath : str) -> None: ...

class Engine:
    def __init__(self, j_str: str) -> None: ...

    def begin(self) -> str: ...
    def layout(self) -> str: ...
    def times(self) -> str: ...
    def process(self, j_str: str) -> str: ...
    def is_on(self) -> bool: ...
    def save(self) -> str: ...
    def load(self, j_str: str) -> None: ...
    def __str__(self) -> str: ...

